### PR TITLE
create soy template decreasing_shape_distance

### PR DESCRIPTION
**Pull request by lilian-hunt**
TODO: create tests

### CODE REVIEW

**Review by jupi3200 — CHANGES_REQUESTED** [review]
Can you please add a screenshot and unit test?

**Review by aannie-y — COMMENTED** [review]
lgtm

**Review by KathleenQ — COMMENTED** [review]
This notice is an error rather than a warning, otherwise, lgtm.

**Comment by lilian-hunt** [comment]
Test created, and changed to error:
Screen Shot 2021-02-10 at 2 51 37 pm

**Review by jupi3200 — APPROVED** [review]

**Pull request merged**
