### PR TITLE
create soy template decreasing_stop_time_distance

### PR DESCRIPTION
**Pull request by lilian-hunt**
TODO: create tests

### CODE REVIEW

**Review by jupi3200 — CHANGES_REQUESTED** [review]
Can you please add a screenshot and unit test?

**Review by aannie-y — COMMENTED** [review]
lgtm

**Review by aannie-y — COMMENTED** [review]
lgtm

**Review by KathleenQ — COMMENTED** [review]
Better to put it as error rather than warning here.

**Comment by lilian-hunt** [comment]
A test has been created
Screen Shot 2021-02-10 at 2 17 01 pm

**Review by jupi3200 — APPROVED** [review]

**Pull request merged**
